import fs from 'fs/promises';
import path from 'path';
import { glob } from 'glob';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.resolve(__dirname, '../src');
const CONTENT_DIR = path.join(SRC_DIR, 'content');
const GENERATED_DIR = path.join(CONTENT_DIR, 'generated');

async function main() {
  const gestureFiles = await glob('gestures/*/gesture.json', { cwd: CONTENT_DIR });
  const flowFiles = await glob('flows/*/flow.json', { cwd: CONTENT_DIR });

  const imports: string[] = [];
  const gestureExports: string[] = [];
  const flowExports: string[] = [];

  gestureFiles.forEach((file, index) => {
    const importName = `gesture_${index}`;
    // relative path from generated/index.ts to gesture.json
    // generated is in src/content/generated
    // gesture is in src/content/gestures/slug/gesture.json
    // relative: ../gestures/slug/gesture.json
    const relativePath = path.join('..', file);
    imports.push(`import ${importName} from '${relativePath}';`);
    gestureExports.push(importName);
  });

  flowFiles.forEach((file, index) => {
    const importName = `flow_${index}`;
    const relativePath = path.join('..', file);
    imports.push(`import ${importName} from '${relativePath}';`);
    flowExports.push(importName);
  });

  const content = `// This file is generated by pnpm content:scan. Do not edit.
import type { Gesture, Flow } from '../../lib/types/content';

${imports.join('\n')}

export const allGestures: Gesture[] = [
  ${gestureExports.join(',\n  ')}
] as unknown as Gesture[];

export const allFlows: Flow[] = [
  ${flowExports.join(',\n  ')}
] as unknown as Flow[];

export const gestureMap = new Map(allGestures.map(g => [g.id, g]));
export const flowMap = new Map(allFlows.map(f => [f.id, f]));
`;

  await fs.mkdir(GENERATED_DIR, { recursive: true });
  await fs.writeFile(path.join(GENERATED_DIR, 'index.ts'), content);

  console.log(`✅ Generated content index with ${gestureFiles.length} gestures and ${flowFiles.length} flows.`);
}

main().catch(console.error);
