import fs from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import { glob } from 'glob';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.resolve(__dirname, '../src');
const CONTENT_DIR = path.join(SRC_DIR, 'content');
const GENERATED_DIR = path.join(CONTENT_DIR, 'generated');

async function main() {
  const gestureFiles = await glob('gestures/*/gesture.json', { cwd: CONTENT_DIR });
  const flowFiles = await glob('flows/*/flow.json', { cwd: CONTENT_DIR });

  const imports: string[] = [];
  const gestureExports: string[] = [];
  const flowExports: string[] = [];

  // Process Gestures
  gestureFiles.forEach((file, index) => {
    const importName = `gesture_${index}`;
    const dir = path.dirname(file); // gestures/slug
    const fullDir = path.join(CONTENT_DIR, dir);
    const hasPoster = existsSync(path.join(fullDir, 'poster.png'));

    const relativePath = path.join('..', file);
    imports.push(`import ${importName}_json from '${relativePath}';`);

    let posterAssignment = '';
    if (hasPoster) {
      const posterVar = `gesture_${index}_poster`;
      imports.push(`import ${posterVar} from '../${dir}/poster.png';`);
      posterAssignment = `poster: ${posterVar},`;
    }

    // Overwrite media.poster
    imports.push(`const ${importName} = {
        ...${importName}_json,
        media: {
            ...${importName}_json.media,
            ${posterAssignment}
        }
    };`);

    gestureExports.push(importName);
  });

  // Process Flows
  flowFiles.forEach((file, index) => {
    const importName = `flow_${index}`;
    const dir = path.dirname(file);
    const fullDir = path.join(CONTENT_DIR, dir);
    const hasPoster = existsSync(path.join(fullDir, 'poster.png'));

    const relativePath = path.join('..', file);
    imports.push(`import ${importName}_json from '${relativePath}';`);

    let posterAssignment = '';
    if (hasPoster) {
      const posterVar = `flow_${index}_poster`;
      imports.push(`import ${posterVar} from '../${dir}/poster.png';`);
      posterAssignment = `poster: ${posterVar},`;
    }

    imports.push(`const ${importName} = {
        ...${importName}_json,
        ${posterAssignment}
    };`);

    flowExports.push(importName);
  });

  const content = `// This file is generated by pnpm content:scan. Do not edit.
import type { Gesture } from '../../lib/types/gesture';
import type { Flow } from '../../lib/types/flow';

${imports.join('\n')}

export const allGestures: Gesture[] = [
  ${gestureExports.join(',\n  ')}
] as unknown as Gesture[];

export const allFlows: Flow[] = [
  ${flowExports.join(',\n  ')}
] as unknown as Flow[];

export const gestureMap = new Map(allGestures.map(g => [g.id, g]));
export const flowMap = new Map(allFlows.map(f => [f.id, f]));
`;

  await fs.mkdir(GENERATED_DIR, { recursive: true });
  await fs.writeFile(path.join(GENERATED_DIR, 'index.ts'), content);

  console.log(`✅ Generated content index with ${gestureFiles.length} gestures and ${flowFiles.length} flows.`);
}

main().catch(console.error);
